mysql:
  path: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: reser
  username: root
  password: "123456"
zap:
  level: info
  format: console
  prefix: "[github.com/zhou-Qingzhang/go-middleware]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
